"""initial schema

Revision ID: 2201ab1ba855
Revises: 
Create Date: 2026-08-23 12:42:55.488473

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2201ab1ba855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwell_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('enter_time', sa.Float(), nullable=False),
    sa.Column('exit_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dwell_sessions_enter_time'), 'dwell_sessions', ['enter_time'], unique=False)
    op.create_index(op.f('ix_dwell_sessions_status'), 'dwell_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_dwell_sessions_track_id'), 'dwell_sessions', ['track_id'], unique=False)
    op.create_index(op.f('ix_dwell_sessions_zone_id'), 'dwell_sessions', ['zone_id'], unique=False)
    op.create_table('zone_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_events_event_type'), 'zone_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_zone_events_timestamp'), 'zone_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_zone_events_track_id'), 'zone_events', ['track_id'], unique=False)
    op.create_index(op.f('ix_zone_events_zone_id'), 'zone_events', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_events_zone_id'), table_name='zone_events')
    op.drop_index(op.f('ix_zone_events_track_id'), table_name='zone_events')
    op.drop_index(op.f('ix_zone_events_timestamp'), table_name='zone_events')
    op.drop_index(op.f('ix_zone_events_event_type'), table_name='zone_events')
    op.drop_table('zone_events')
    op.drop_index(op.f('ix_dwell_sessions_zone_id'), table_name='dwell_sessions')
    op.drop_index(op.f('ix_dwell_sessions_track_id'), table_name='dwell_sessions')
    op.drop_index(op.f('ix_dwell_sessions_status'), table_name='dwell_sessions')
    op.drop_index(op.f('ix_dwell_sessions_enter_time'), table_name='dwell_sessions')
    op.drop_table('dwell_sessions')
    op.drop_table('zones')
    # ### end Alembic commands ###
